In [ ]:
from sklearn.datasets import load_iris
li=load_iris()
x=li.data
y=li.target
from sklearn.preprocessing import MinMaxScaler
scale=MinMaxScaler()
x1=scale.fit_transform(x)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
#convert binary & integer
import numpy as np
#data3=np.array(y)
from sklearn.preprocessing  import OneHotEncoder
ohe=OneHotEncoder()
y1=ohe.fit_transform(y[:,np.newaxis]).toarray()
y2=y1.astype('int')
y2

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [ ]:
#split data
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x1,y2,test_size=0.2)

In [ ]:
#make model& train data
#from keras.activations import softmax
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(12,activation='relu',input_dim=4))
model.add(Dense(12,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(optimizer='adam',loss='categorical_crossentropy')
model.fit(xtrain,ytrain,epochs=100)

Epoch 1/100
4/4 [==============================] - 1s 3ms/step - loss: 1.1325
Epoch 2/100
4/4 [==============================] - 0s 4ms/step - loss: 1.1207
Epoch 3/100
4/4 [==============================] - 0s 3ms/step - loss: 1.1114
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 1.1038
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0960
Epoch 6/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0885
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0823
Epoch 8/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0759
Epoch 9/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0698
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0639
Epoch 11/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0571
Epoch 12/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0498
Epoch 13/100
4/4 [==============================] - 0s 3ms/st

In [ ]:
ypred=model.predict(xtest)

1/1 [==============================] - 0s 79ms/step


In [ ]:
for i in range(len(ypred)):
  j=np.argmax(ypred[i,:])
  ypred[i,0]=0
  ypred[i,1]=0
  ypred[i,2]=0
  ypred[i,j]=1
   

In [ ]:
ypred.astype('int')

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [ ]:
def accuracy(y1,y):
  correct=0
  for a,b in zip(y1,y):
    if a==b:
      correct+=1
  return correct/len(y1)    

In [ ]:
accuracy(ypred.tolist(),ytest.tolist())

0.9333333333333333